### ISSUE TITLE
how to setup two systems between the firewall.

### ISSUE THREAD

**Issue by mmali277** [P1sec/SigFW#10]
i have all the systems configured, i.e i have restcomm smsc gateway, by which we are sending messages over ss7 through smsc gateway between two systems (laptops) using jss7 simulator and sip phone. 

Now i want know how i configure the vm between the two systems so that i can get logs of messages on firewall between them. i know that vm uses enp0s9 interface to capture traffic but i need some guidance.
Thank you.

**Comment by p1-martin** [comment]
@mmali277 
For firewall:
1. (In VM) stop all services [ss7client](https://github.com/P1sec/SigFW/blob/master/VM/ss7client.service), [ss7server](https://github.com/P1sec/SigFW/blob/master/VM/ss7server.service), [ss7fw](https://github.com/P1sec/SigFW/blob/master/VM/ss7fw.service), [tshark_to_ss7fw](https://github.com/P1sec/SigFW/blob/master/VM/tshark_to_ss7fw.service)
2. You have to edit the SS7 firewall config (ss7fw.json). There is "sctp_server" block where you need to configure the IP address and port where the SS7FW will listen. Then configure SS7 client in "sctp_server_association" block. And configure the SS7 server in "sctp_association" block. (See the "assoc_name" in these blocks to identify easier these SCTP associations).
3. To apply config: delete the ss7fw.json.last and start SS7FW   (the .last files are generated and periodically stored during runtime. On startup they are used only if they exist in the folder. Otherwise the .json config is used. The reason for this is the FW config can be changed also over API, so it reflects the runtime configuration which is periodically stored in that .last files)
4. Start only the service [ss7fw](https://github.com/P1sec/SigFW/blob/master/VM/ss7fw.service) (just SS7FW)
5. Start your SS7 client and your SS7 server which would interconnect with the SS7FW.   (it can be STP -> SS7FW -> STP or for your tests maybe SMSC -> SS7FW -> SS7Server)
6. You can monitor if the SS7FW works and was interconnected properly by checking the sigfw.log or checking the API https://ss7fw_management_ip:8443/ss7fw_api/1.0/get_status to see the link status or using wireshark/tshark to check if the M3UA links went up.

For elastic + kibana monitoring:
1. there are the light scripts to import the data into elasticsearch. It is just sufficient to locate and edit the script [tshark_to_ek.sh](https://github.com/P1sec/SigFW/blob/master/VM/tshark_to_ek.sh). And configure there the proper interface, where the traffic would be captured.
2. (In VM) Restart the service [tshark_to_ek](https://github.com/P1sec/SigFW/blob/master/VM/tshark_to_ek.service)
3. If this is working properly you should seen new messages appeared in Kibana

**Comment by mmali277** [comment]
# SCTP Server

![screenshot from 2018-02-20 19-17-43](https://user-images.githubusercontent.com/24794007/36429433-9b29e42a-164a-11e8-960d-c76ec05c1020.png)

# SCTP Association
![screenshot from 2018-02-20 19-19-34](https://user-images.githubusercontent.com/24794007/36429446-9f8378ba-164a-11e8-846d-e75a89bb0a1e.png)

# sigfw.json configuration
![28278919_1614082602007238_2033240762_o](https://user-images.githubusercontent.com/24794007/36429912-c2959184-164b-11e8-8c05-ae6b649ce404.png)


Smsc is running on jboss on 172.20.16.65
now this link https://ss7fw_management_ip:8443/ss7fw_api/1.0/get_status is not working.

management ip of vm : 172.20.16.161
monitoring ip of vm: 172.20.16.163
Please guide me.

**Comment by p1-martin** [comment]
@mmali277 
You need to reconfigure SMSC too. If you want this setup SMSC -> SS7FW -> SS7Server you have to configure SMSC association as "client".
In your screen shots there is localhost IP 127.0.0.1. You should configure there SMSC host address to 172.20.16.65 and server port (8016 according to ss7fw.json). After the peer address to IP of SS7FW 172.20.16.161 and peer port to 8015 according to your ss7fw.json

The following link for API in your case should work:  https://172.20.16.161:8443/ss7fw_api/1.0/get_status

**Comment by p1-martin** [comment]
@mmali277 
My point was that you need to configure both SS7FW and also SMSC and I seen in previous screenshots the localhost addresses.

If you would like to use signalling ip of ss7fw vm then I think you should do the following:
1.) On SMSC:
The host address should be 172.20.16.65 and host port should be 8015.  (the addresses of SMSC) 
Peer address should be 172.20.16.162 and peer port 8016.  (the address of SS7FW, this is the peer.)

2.) On SS7FW: Peer address "sctp_server_association" should IP of SMSC. 172.20.16.65

3.) On SS7FW: "sctp_association" in sigfw.json is the output side from the SS7FW. The firewall has INPUT and OUTPUT associations. And Firewall is in path between two network elements (without having SCCP GT, but having IP and M3UA point code). So the question is where you want to forward the traffic. SMSC -> SS7FW -> ?    (for testing you can keep there SS7Server and the original config. And run the service ss7server in the VM).   

4.) On SS7FW: "sctp_server" in sigfw.json configure there the signalling ip of vm (172.20.16.162)

**Comment by mmali277** [comment]
For testing purposes I want to send messages (on a single ip i.e 172.20.16.65) from jss7 simulator to smpp simulator (which is working). I want to route traffic from firewall.

**Comment by mmali277** [comment]
In upper question:
In Smsc we have two things:
1.) sctp server:
2.) sctp association:

In these both, host address and host port are same...
So i changed host port to 8019 in association. now the error ( in  previous question) is removed but new errora are showing, which are:
1.) 
17:03:23,860 ERROR [M3UAManagementImpl] (SLEE-EventRouterExecutor-1-thread-1) Tx : No AS found for routing message TransferMessage: {528=Protocol opc=2 dpc=1 si=3 ni=2 sls=1}


2.)
17:03:25,183 ERROR [SelectorThread] (Thread-37) Exception while finishing connection for Association=ass1
java.net.ConnectException: Connection refused
	at sun.nio.ch.sctp.SctpChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.sctp.SctpChannelImpl.finishConnect(SctpChannelImpl.java:482)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnectionSctp(SelectorThread.java:381)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnection(SelectorThread.java:366)
	at org.mobicents.protocols.sctp.SelectorThread.run(SelectorThread.java:151)
	at java.lang.Thread.run(Thread.java:748)


Also the link :  https://172.20.16.162:8443/ss7fw_api/1.0/get_status is still not working

**Comment by p1-martin** [comment]
@mmali277 
- Check if you have IP connectivity first between the VMs. Try ping the IPs in both directions.
- Check if you see open SCTP port on the SS7FW. You can use nmap -Pn -sY -p&lt;port&gt; &lt;host&gt;
- After, trace the SMSC communication to see where is problem (if you receive SCTP abort from other side or no response, and so on ...). To confirm if there is SCTP association established
- After there need to be established M3UA. Based on the error above also verify the point codes configured in ss7fw.json in the block "m3ua".

Regarding the API, this is minor/support function and not directly related with association setup. It should be running on SS7FW, there is embedded jetty server providing this API. You can use netstat to see in SS7FW VM where is 8443 listening. Also not sure from where you are trying to connect. Check the IP connectivity first.

**Comment by mmali277** [comment]
1.) port 8443 is closed in ubuntu vm. dont know why? 
2.)please also answer the question asked before the previous one and also tell if the configuration is correct. 
3.)My other machine is kali. and both vm and kali are pinging each other.

**Comment by p1-martin** [comment]
@mmali277 
1.) I mentioned in previous post to you to use netstat to see on which IP the port 8443 is bind in your VM 
2.) You first time mentioned port 8019 in your previous question. I don't understand why, because previously there was other ports mentioned.

Also please note that the github issues here should be used mainly to report problems and bugs which are related to the source code available in this repository, unfortunately not to provide extensive support with troubleshooting. Additionally I would recommend the following:
- To check publicly available guides how to setup SCTP/M3UA, there are available also guides for jSS7. 
- You can use the initial version running on the localhost which has worked for you. To compare and trace the discrepancies with your current deployment: trace and compare 2 pcaps (one from localhost and the other from your deployment). Compare messages and see in which steps the interconnection exactly fails.

**Comment by mmali277** [comment]
Thankyou Sir for your help, Sorry for irrelevent questions.
