### ISSUE TITLE
Unable to find out input dir to run pcap files using tshark.

### ISSUE THREAD

**Issue by vnittur** [P1sec/SigFW#12]
I have downloaded and built the project as per the instructions provided in readme and jss7 branch. 
Can you please help where to find diameter.pcap & sigtran.pcap.

**Comment by p1-martin** [comment]
@vnittur 
You can use any sigtran and diameter pcap which you found on internet or which were captured from some network. Additionally if there is no pcap you can use SS7Client/DiameterClient and craft messages programatically instead of SS7ClientLiveInput/DiameterClientLiveInput. For sigtran.pcap crafted artificially and which was used for SigFW demo, you can refer to this [page](https://www.h21lab.com/tools/ss7-libmich).
