### ISSUE TITLE
XmlSctpFirewall/sctp_mgmt_sctp.xml (No such file or directory)

### ISSUE THREAD

**Issue by mmali277** [P1sec/SigFW#6]
[ss7fw.SS7Firewall.main()] WARN  org.mobicents.protocols.sctp.ManagementImpl  - Failed to load the SCTP configuration file. 
XmlSctpFirewall/sctp_mgmt_sctp.xml (No such file or directory)

//(while the file is there.) AND AFTER SOME LINES:

10581 [Thread-10] ERROR org.mobicents.protocols.sctp.SelectorThread  - Exception while finishing connection for Association=sctp_from_firewall_to_server
java.net.ConnectException: Connection refused
	at sun.nio.ch.sctp.SctpChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.sctp.SctpChannelImpl.finishConnect(SctpChannelImpl.java:482)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnectionSctp(SelectorThread.java:381)
	at org.mobicents.protocols.sctp.SelectorThread.finishConnection(SelectorThread.java:366)
	at org.mobicents.protocols.sctp.SelectorThread.run(SelectorThread.java:151)
	at java.lang.Thread.run(Thread.java:748)

**Comment by p1-martin** [comment]
Hi mmali277,

The XmlSctpFirewall/sctp_mgmt_sctp.xml belongs to class ss7fw/SS7Firewall and the xml should be created during the firewall run. Try running SS7Server, then SS7Firewall and then SS7Client. The xml files should be created during the first run. 

You can run it from IDE (e.g. netbeans) or from command line, but you should be in correct folder (./SigFW/sigfw/sigfw.sigfw/). See wiki pages https://github.com/P1sec/SigFW/wiki/Cheat-Sheet.
After you can monitor the status of sctp links by wireshark or in sigfw.log or by checking the status API (https://<host>:8443/ss7fw_api/1.0/get_status).  

Also note, when running maven test before running the project, this could also rise this error. Because the xml files do not exist yet.

If the problem persists, I think there could be some problem with current working directory.
Then let me know how you are running the project from netbeans, command line or as a service (e.g. by using the service scripts https://github.com/P1sec/SigFW/tree/master/VM).

**Comment by mmali277** [comment]
@p1-martin  Thank you, the sequence you defined for setting up the network resolved my issue. the result of this link (https://:8443/ss7fw_api/1.0/get_status) is as follow:




Jetty Server Status = STARTED
Jetty Date = Date: Tue, 06 Feb 2018 08:54:33 GMT
Jetty URI = https://127.0.1.1:8443/

SCTP Associations
 Name = sctp_from_client_to_firewall
 Details = Association [name=sctp_from_client_to_firewall, associationType=SERVER, ipChannelType=SCTP, hostAddress=null, hostPort=0, peerAddress=127.0.0.1, peerPort=2345, serverName=sctp_server, extraHostAddress=[]]
 isStarted = true
 isConnected = true
 Name = sctp_from_firewall_to_server
 Details = Association [name=sctp_from_firewall_to_server, associationType=CLIENT, ipChannelType=SCTP, hostAddress=127.0.0.1, hostPort=2344, peerAddress=127.0.0.1, peerPort=3434, serverName=null, extraHostAddress=[]]
 isStarted = true
 isConnected = true

SCTP Servers = {Server [name=sctp_server, started=true, hostAddress=127.0.0.1, hostPort=3433, ipChannelType=SCTP, acceptAnonymousConnections=false, maxConcurrentConnectionsCount=0, associations(anonymous does not included)=[sctp_from_client_to_firewall, ], extraHostAddress=[]]}

M3UA Server
 Name = RAS1
 isConnected = true
 isUp = true
M3UA Server Route = {1:-1:-1=org.mobicents.protocols.ss7.m3ua.impl.RouteAsImpl@239826b8}

M3UA Client
 Name = AS1
 isConnected = true
 isUp = true
M3UA Client Route = {2:-1:-1=org.mobicents.protocols.ss7.m3ua.impl.RouteAsImpl@b7c0cab}

SCCP M3UA User Parts = {0=rsp=1 rsp-flag=0 mask=0 rsp-prohibited=false rsccp-prohibited=false rl=0 rsl=0, 1=rsp=2 rsp-flag=0 mask=0 rsp-prohibited=false rsccp-prohibited=false rl=0 rsl=0}

OS statistics
 Available processors (cores): 4
 Free memory (bytes): 300993424
 Maximum memory (bytes): 1793589248
 Total memory available to JVM (bytes): 382730240
 File system root: /




I am new to this field, so i would require and appreciate your help a lot.  I am able to monitor only sctp packets on loop back address, so i wnat to ask:
1) How can i generate m3ua, SCCP etc (SS7 network protocols) traffic so that we can monitor it. 
2) If i am using wrong IP addresses, then in which file i can change these settings.
3) How it acts like a honeypot (as it have a class ss7 honeypot).
![Uploading Screenshot from 2018-02-06 14-36-56.png…]()

P.S : sorry for the late reply and Thanks in advance

**Comment by p1-martin** [comment]
@mmali277 
Good that it is working. So I will close this xml issue now.

Regarding your other questions:
1. You don't need to generate M3UA because it is protocol used to establish link between adjacent nodes. So the SS7Client/SS7ClientLiveInput, SS7FW, SS7Server are establishing the M3UA links for you. 
For crafting MAP/SCCP messages there are several options:
- You can craft it problematically in SS7Client.java by using jSS7. 
- You can use existing pcap by using SS7ClientLiveInput (see "Replay traffic from pcap" in  [README.md](https://github.com/P1sec/SigFW#replay-traffic-from-pcap))
- You can use any other SS7 client/library/real_network_element to connect to SS7FW
2. To change IP addresses, there is ss7fw.json configuration file. (and diameterfw.json for diameter firewall). To change the IPs in SS7 client and SS7 server, you need to change it grammatically in SS7Client/SS7ClientLiveInput (depending which one you will use) and SS7Server.

3. Regarding honeypot I would recommend to read the slides in [doc](https://github.com/P1sec/SigFW/tree/master/docs) folder to understand this feature. For full deployment you need real STP or SCCP router instead of SS7Client and SS7Server with real SCCP routing and route it towards the honeypot. 
The honeypot policy of firewall can be enabled by changing the default policy to DNAT_TO_HONEYPOT in ss7fw.json config and by honeypot statement in the same config. If enabled then the firewall is changing the Called GT (in SCCP layer), i.e. it is performing Destination NAT for all illegal traffic. Then the SS7Honeypot.java class, which has very limited functionality in current repo, can be used to deploy such SS7 honeypot with its own SCCP GT in the SS7 network. But without STP you can just run isolated tests. (using SS7Honeypot.java instead of SS7Server.java)
