### ISSUE TITLE
How to Monitor GSM traffic using SigFW

### ISSUE THREAD

**Issue by Kawish-Ali** [P1sec/SigFW#7]
How to monitor GSM traffic on SigFW honeypot?
What are the configurations of IP addresses of client and host?

**Comment by p1-martin** [comment]
@Kawish-Ali 
SigFW honeypot feature forwards to honeypot the traffic which is detected by SigFW as illegal (instead of dropping the traffic or sending error. And this is configured by firewall policy in config file). The added value of honeypot is, that it can actually answer to illegal/hostile signalling in a more sophisticated way (for example, providing wrong localization data to hostile localization queries). Currently to enable this functionality the SCCP routing is required in the network (i.e. the full integration of SigFW with STP). And the honeypot need to be deployed as separate network element inside the network and be reachable with its own GT (by SCCP routing on GT). The SigFW is doing the DNAT towards this honeypot and is modifying the illegal /hostile signalling traffic to forward it to honeypot (modifying the called GT in SCCP layer back and forth). Also it should be noted that the current SS7Honeypot code included in this repo is very light and used just for demonstration with hardcoded values.

For monitoring of alerts from the SigFW there is API (HTTP REST) to mThreat to report detected events. So for purpose of receiving the security alerts from the SigFW this is the proper way. 

For pure monitoring solutions of signalling traffic:
- For signalling security monitoring (compliant with GSMA monitoring guidelines) there is available product [P1 PTM](http://www.p1sec.com/corp/products/p1-telecom-monitor-ptm/) (Signalling IDS, which can be integrated with SigFW)
- For generic protocol monitoring/analytics you can use [tshark + elasticsearch](https://www.h21lab.com/tools/tshark-elasticsearch) or other telecom monitoring systems

For IP configuration of SigFW, there is [ss7fw.json](https://github.com/P1sec/SigFW/blob/master/sigfw/sigfw.sigfw/ss7fw.json) and [diameterfw.json](https://github.com/P1sec/SigFW/blob/master/sigfw/sigfw.sigfw/diameterfw.json) configs.

**Comment by p1-martin** [comment]
@Kawish-Ali
And also you can use SigFW in passive mode, everything running on localhost in the following way: 
passive traffic (pcap or port mirror) -> tshark -> ek json -> input pipe -> SS7ClientLiveInput -> SS7FW -> SS7Server.

I will close this issue for now, but it can be reopened if needed.
